### ISSUE TITLE
Support for Clang 15

### ISSUE THREAD

**Issue by xairy** [a13xp0p0v/kernel-build-containers#10]
It would be nice to add support for Clangs 15+ to enable building KMSAN and for [better KASAN support](https://reviews.llvm.org/D122724).

LLVM provides an [apt repository](https://apt.llvm.org/) for Clang. An example reference of a Dockerfile can be found in [syzkaller repo](https://github.com/google/syzkaller/pull/3651/files).

Thank you!

**Comment by a13xp0p0v** [comment]
Hello @xairy,

Got some time to work on this.

It turned out that Ubuntu 22.04 supports clang-15. I've added a new container with it.

Is it fine? Do you need a separate container with a bleeding-edge fresh clang from the LLVM apt repository?

**Comment by xairy** [comment]
Yes, Clang 15 is what I needed. Thank you a lot!
