### ISSUE TITLE
Fail loudly when kernel build fails

### ISSUE THREAD

**Issue by xairy** [a13xp0p0v/kernel-build-containers#3]
Currently it's not very clear when a build fails, as both a failed and a successful builds have the same last few lines:

```
Running the container returned 0
See build log: .../build_log.txt

[+] Done, see the results
```

**Comment by a13xp0p0v** [comment]
Hi @xairy 
May I ask you to try it now?
Thanks!

**Comment by xairy** [comment]
Looks much better now, thanks!

`[+]` at the end is still a bit confusing, but I think this is fine.

```
      LD [M]  fs/nfs/flexfilelayout/nfs_layout_flexfiles.o
      AR      fs/nfs/built-in.a
      AR      fs/built-in.a
    make[1]: Leaving directory '/home/user/out'
    make: *** [Makefile:185: __sub-make] Error 2
Running the container returned 2
See build log: .../build_log.txt

[+] Done, see the results
```

**Comment by a13xp0p0v** [comment]
This tool can build several kernels during one run (if you specify several compilers with `-c`).
So this `[+] Done` shows that the tool really finished its jobs :)

**Comment by xairy** [comment]
OK, SGTM, thanks you for the fix! :)
