### ISSUE TITLE
Unprivileged container support

### ISSUE THREAD

**Issue by ghost** [a13xp0p0v/kernel-build-containers#5]
Hi,

I have adapted the code to use a -cap_all and non privileged user + immutable filesystem to build the kernels.
However, I have not adapted make_linux.py to support it yet. I'm adding this as a reminder, if I have some time to prepare the code and send it over, or if you wish to implement it your own way.

**Comment by a13xp0p0v** [comment]
Hi @vogelfreiheit,

I'm looking forward to testing your pull request.

**Comment by a13xp0p0v** [comment]
Closing the issue since the @vogelfreiheit account has been deleted.
