### ISSUE TITLE
Support building Rocky Linux RPM packages with custom patches

### ISSUE THREAD

**Issue by ghost** [a13xp0p0v/kernel-build-containers#6]
I'm opening this to remind myself that I should clean up the modifications I have made to use rpmbuilder for building el8 RPM packages.

The only catch is I'm going the patching manually, in the spec file.

**Comment by a13xp0p0v** [comment]
Hi @vogelfreiheit,

I'm looking forward to testing your pull request.

**Comment by a13xp0p0v** [comment]
Closing the issue since the @vogelfreiheit account has been deleted.
