### ISSUE TITLE
Investigate support for menuconfig

### ISSUE THREAD

**Issue by xairy** [a13xp0p0v/kernel-build-containers#9]
It would be nice if `menuconfig` worked via the `./make_linux.py` script.

**Comment by a13xp0p0v** [comment]
Hey @xairy,

Now we can configure the Linux kernel with `menuconfig` in the needed container.

The `make_linux.py` tool supports the interactive mode for `make menuconfig`.

Please have a try!

https://github.com/a13xp0p0v/kernel-build-containers?tab=readme-ov-file#building-linux-kernel

**Comment by xairy** [comment]
Tested, works! Thanks a lot!
